"""
Test corpus of 1,000 sentences for tokenizer comparison analysis.
8 categories covering diverse text types.
"""

SIMPLE_ENGLISH = [
    "The cat sat on the mat.",
    "She opened the door and walked inside.",
    "It was a bright sunny day.",
    "He drove to the store to buy milk.",
    "The children played in the park.",
    "I had coffee and toast for breakfast.",
    "The dog barked at the mailman.",
    "We went for a walk after dinner.",
    "She smiled and waved goodbye.",
    "The book was on the table.",
    "They arrived at the airport on time.",
    "He turned off the lights and went to bed.",
    "Rain fell steadily throughout the night.",
    "The flowers bloomed in the spring garden.",
    "She answered the phone on the first ring.",
    "The bus stopped at the corner.",
    "He read the newspaper every morning.",
    "We watched a movie last night.",
    "The baby fell asleep in the crib.",
    "She cooked dinner for the whole family.",
    "The train arrived at platform three.",
    "He wore a blue jacket and jeans.",
    "They celebrated his birthday with a cake.",
    "The teacher wrote on the blackboard.",
    "She found her keys in her pocket.",
    "The wind blew the leaves off the trees.",
    "He finished his homework before dinner.",
    "We sat by the fire and talked.",
    "The store closes at nine o'clock.",
    "She took the dog for a walk.",
    "The sun set behind the mountains.",
    "He washed the dishes after eating.",
    "They went swimming in the lake.",
    "The car broke down on the highway.",
    "She planted tomatoes in the backyard.",
    "The meeting starts at ten in the morning.",
    "He caught the ball with one hand.",
    "We ordered pizza for lunch.",
    "The music played softly in the background.",
    "She packed her bag for the trip.",
    "The snow covered the ground in white.",
    "He opened the window to let in air.",
    "They waited for the bus in the rain.",
    "The clock struck midnight.",
    "She drew a picture of a horse.",
    "The bridge crossed over the river.",
    "He put on his coat and left.",
    "We sang songs around the campfire.",
    "The phone rang during dinner.",
    "She locked the door behind her.",
    "The sky was full of stars.",
    "He mowed the lawn on Saturday.",
    "They played cards all afternoon.",
    "The water boiled in the kettle.",
    "She tied her hair in a ponytail.",
    "The movie lasted two hours.",
    "He climbed the stairs to the top floor.",
    "We picked apples from the tree.",
    "The restaurant was crowded tonight.",
    "She wrote a letter to her friend.",
    "The plane took off at noon.",
    "He fixed the leaky faucet.",
    "They danced at the wedding reception.",
    "The moon shone brightly overhead.",
    "She set the alarm for six o'clock.",
    "The birds sang in the early morning.",
    "He walked home from school.",
    "We cleaned the house before guests arrived.",
    "The kitten chased a ball of yarn.",
    "She hung the painting on the wall.",
    "The lake was calm and still.",
    "He bought flowers for his wife.",
    "They moved to a new apartment.",
    "The bell rang at the end of class.",
    "She poured milk into the cereal bowl.",
    "The garden gate creaked when opened.",
    "He counted the coins in his pocket.",
    "We drove through the countryside.",
    "The lamp flickered in the dark room.",
    "She folded the laundry neatly.",
    "The road was empty at midnight.",
    "He brushed his teeth before bed.",
    "They cheered when the team scored.",
    "The cake tasted sweet and creamy.",
    "She returned the book to the library.",
    "The leaves turned orange in autumn.",
    "He parked the car in the garage.",
    "We played chess on Sunday evening.",
    "The soup was hot and delicious.",
    "She wrapped the gift with ribbon.",
    "The door opened with a loud creak.",
    "He sipped his tea slowly.",
    "They built a sandcastle on the beach.",
    "The fire crackled in the fireplace.",
    "She watered the plants every morning.",
    "The streets were quiet at dawn.",
    "He tossed the ball to his son.",
    "We hiked to the top of the hill.",
    "The curtains blew in the breeze.",
    "She peeled an orange for a snack.",
    "The old house stood at the end of the lane.",
    "He adjusted his glasses and began reading.",
    "They shared a slice of pie.",
    "The ice cream melted in the sun.",
    "She hummed a tune while cooking.",
    "The alarm went off at seven sharp.",
    "He carried the groceries into the kitchen.",
    "We planted a tree in the front yard.",
    "The test was easier than expected.",
    "She crossed the street at the light.",
    "The thunder rumbled in the distance.",
    "He sharpened the pencil with a knife.",
    "They explored the cave with flashlights.",
    "The horse galloped across the field.",
    "She swept the floor after the party.",
    "The coffee shop opened early.",
    "He tied his shoes and headed out.",
    "We listened to music on the drive.",
    "The owl hooted from the tree branch.",
    "She sliced the bread for sandwiches.",
    "The fountain splashed water into the air.",
    "He painted the fence white.",
    "They laughed at the joke.",
    "The map showed the quickest route.",
    "She stirred the pot of stew.",
    "The bicycle leaned against the wall.",
    "He whistled while he worked.",
    "We gathered around the dining table.",
    "The library was quiet and peaceful.",
    "She caught the early morning train.",
    "The waves crashed against the rocks.",
    "He flipped the pancakes in the pan.",
    "They decorated the room for the party.",
    "The squirrel ran up the oak tree.",
    "She zipped up her jacket in the cold.",
    "The garage door opened slowly.",
    "He stacked the firewood by the shed.",
    "We stayed up late watching television.",
    "The river flowed gently through the valley.",
    "She counted the stars in the sky.",
    "The toaster popped the bread out.",
    "He kicked the soccer ball across the yard.",
    "They waited in line at the counter.",
    "The elevator went to the fifth floor.",
    "She dusted the shelves in the living room.",
    "The clouds drifted slowly across the sky.",
    "He leaned against the fence post.",
    "We ate lunch under the big tree.",
    "The neighbor waved from across the street.",
    "She trimmed the hedges along the walkway.",
    "The candle burned down to a stub.",
    "He rolled up his sleeves and got to work.",
    "They collected seashells along the shore.",
    "The kettle whistled on the stove.",
    "She glanced at her watch and hurried along.",
    "The stadium was packed with fans.",
    "He folded the paper into an airplane.",
    "We admired the view from the balcony.",
    "The rabbit hopped across the lawn.",
    "She pulled the weeds from the flower bed.",
    "The taxi arrived in five minutes.",
    "He stretched before his morning run.",
    "They exchanged gifts under the tree.",
    "The bakery smelled of fresh bread.",
    "She checked the mailbox every afternoon.",
    "The kite soared high above the park.",
    "He tightened the bolt with a wrench.",
    "We ate dinner by candlelight.",
    "The clock on the wall needed new batteries.",
    "She braided her daughter's hair.",
    "The sunset painted the sky in shades of pink.",
    "He buttoned his shirt and looked in the mirror.",
    "They rode their bikes to the pond.",
    "The newspaper landed on the front porch.",
    "She arranged flowers in a vase.",
    "The cat curled up by the window.",
    "He scraped the ice off the windshield.",
    "We made lemonade with fresh lemons.",
    "The rooster crowed at the crack of dawn.",
    "She handed the report to her manager.",
    "The swing swayed gently in the park.",
    "He dropped a coin into the wishing well.",
    "They watched the fireworks from the rooftop.",
    "The mailman delivered a large package.",
    "She ironed her dress for the interview.",
    "The frog jumped into the pond.",
    "He carved his initials into the tree.",
    "We found a quiet spot by the stream.",
    "The lights turned green and traffic moved.",
    "She rinsed the vegetables under the tap.",
    "The ship sailed out of the harbor.",
    "He hung his coat on the hook by the door.",
    "They set up the tent near the lake.",
    "The spider spun a web in the corner.",
    "She recited the poem from memory.",
]

COMPLEX_ENGLISH = [
    "The juxtaposition of classical Baroque architecture with brutalist concrete facades creates an unsettling cognitive dissonance in the city's downtown core.",
    "Notwithstanding the defendant's protestations of innocence, the preponderance of circumstantial evidence rendered the jury's verdict virtually inevitable.",
    "The pharmacokinetic properties of the novel anticoagulant demonstrate superior bioavailability compared to existing thrombin inhibitors in randomized controlled trials.",
    "Epistemological relativism, when taken to its logical extreme, paradoxically undermines the very argumentative framework upon which it depends for its own justification.",
    "The superconducting quantum interference device measured fluctuations in the magnetic flux at the femtotesla level, enabling unprecedented neuroimaging resolution.",
    "Anthropogenic perturbation of biogeochemical cycles has accelerated eutrophication in freshwater ecosystems, precipitating cascading trophic disruptions.",
    "The hermeneutical circle presents an interpretive paradox: one cannot understand the parts without grasping the whole, yet the whole is constituted by its parts.",
    "Quantitative easing, while ostensibly a tool for monetary expansion, has disproportionately inflated asset prices, exacerbating wealth inequality across socioeconomic strata.",
    "The patient presented with paroxysmal nocturnal dyspnea, orthopnea, and bilateral pedal edema consistent with decompensated congestive heart failure.",
    "Deconstructionist literary criticism interrogates the stability of signifier-signified relationships, revealing the inherent polysemy embedded within ostensibly univocal texts.",
    "The commissural fibers of the corpus callosum facilitate interhemispheric communication, enabling the integration of lateralized cognitive functions across the cerebral cortex.",
    "Stochastic gradient descent with momentum and adaptive learning rate scheduling converges more reliably on non-convex loss surfaces than vanilla gradient descent.",
    "The paleontological record suggests that the Permian-Triassic extinction event eliminated approximately ninety-six percent of all marine species within a geologically brief interval.",
    "Jurisprudential analysis of the dormant commerce clause reveals an inherent tension between state police powers and the constitutional imperative of unfettered interstate commerce.",
    "Heisenberg's uncertainty principle establishes a fundamental epistemological limit on the simultaneous determination of conjugate variables such as position and momentum.",
    "The longitudinal epidemiological study demonstrated a statistically significant inverse correlation between Mediterranean dietary adherence and the incidence of neurodegenerative pathology.",
    "Phenomenological reduction, as articulated by Husserl, requires the systematic bracketing of all naturalistic assumptions to access the structures of pure consciousness.",
    "The endoplasmic reticulum's role in calcium homeostasis is critical for maintaining proper cellular signaling cascades and preventing apoptotic pathway activation.",
    "Contrapuntal polyphony in Bach's fugues demonstrates the mathematical precision with which multiple independent melodic voices can be woven into a harmonically coherent tapestry.",
    "The geopolitical ramifications of semiconductor supply chain concentration in East Asia represent a significant vulnerability in the global technological infrastructure.",
    "Interleukin-6 mediated inflammatory signaling through the JAK-STAT pathway plays a pivotal role in the pathogenesis of cytokine release syndrome.",
    "The Navier-Stokes equations governing viscous fluid dynamics remain one of the unsolved Millennium Prize Problems in mathematical physics.",
    "Cryptographic hash functions must exhibit preimage resistance, second preimage resistance, and collision resistance to be considered computationally secure.",
    "The thalamic reticular nucleus serves as a gating mechanism, modulating the flow of sensory information between the thalamus and cortical processing areas.",
    "Photovoltaic cells employing perovskite-silicon tandem architectures have achieved power conversion efficiencies exceeding thirty percent in laboratory conditions.",
    "The categorical imperative, Kant's supreme principle of morality, demands that one act only according to maxims that could simultaneously serve as universal laws.",
    "Metagenomic sequencing of the human gut microbiome has revealed previously uncharacterized bacterial taxa with significant implications for immunological homeostasis.",
    "The efficient market hypothesis, in its strong form, asserts that asset prices instantaneously incorporate all available information, rendering fundamental analysis superfluous.",
    "Synchrotron radiation spectroscopy enables the characterization of electronic band structure in novel topological insulators with unprecedented energy resolution.",
    "The Treaty of Westphalia established the foundational principles of territorial sovereignty and non-interference that continue to undergird the contemporary international order.",
    "Allosteric regulation of enzyme activity through conformational changes induced by effector molecules represents a sophisticated mechanism of metabolic pathway control.",
    "The philosophical zombie thought experiment challenges physicalist accounts of consciousness by positing a being functionally identical to a human but lacking subjective experience.",
    "Magnetohydrodynamic instabilities in tokamak plasma confinement devices remain a primary obstacle to achieving sustained thermonuclear fusion energy production.",
    "The prodromal phase of schizophrenia is characterized by attenuated psychotic symptoms, social withdrawal, and declining functional capacity preceding the first psychotic episode.",
    "Lithographic patterning at extreme ultraviolet wavelengths enables the fabrication of semiconductor features at the sub-seven-nanometer node.",
    "The Sapir-Whorf hypothesis, in its strong form of linguistic determinism, posits that the structure of language fundamentally constrains the categories of thought available to its speakers.",
    "Riemann's zeta function and its non-trivial zeros are intimately connected to the distribution of prime numbers through the explicit formulae of analytic number theory.",
    "The amygdala's role in fear conditioning involves long-term potentiation at thalamo-amygdalar synapses, consolidating associative memories between neutral stimuli and aversive outcomes.",
    "Transcranial magnetic stimulation applied to the dorsolateral prefrontal cortex has demonstrated therapeutic efficacy in treatment-resistant major depressive disorder.",
    "The Chandrasekhar limit of approximately 1.4 solar masses determines whether a white dwarf will undergo gravitational collapse into a neutron star or black hole.",
    "Recursive self-improvement in artificial general intelligence systems presents an existential risk if alignment between system objectives and human values cannot be formally guaranteed.",
    "The jurisprudence surrounding qualified immunity has been criticized for creating perverse incentives that shield governmental actors from accountability for constitutional violations.",
    "Bayesian hierarchical models with weakly informative priors provide a principled framework for borrowing statistical strength across related experimental units.",
    "The double-slit experiment illustrates the fundamental wave-particle duality of quantum mechanics, with observation itself altering the behavior of subatomic particles.",
    "Retrograde amnesia following bilateral hippocampal lesions demonstrates the critical role of the medial temporal lobe in the consolidation of declarative episodic memories.",
    "The Anthropocene epoch, though not yet formally ratified by the International Commission on Stratigraphy, marks a period of unprecedented human geological impact.",
    "Variational autoencoders learn a continuous latent representation by optimizing the evidence lower bound on the marginal log-likelihood of the observed data.",
    "The peripatetic philosophers of ancient Greece conducted their dialectical inquiries while ambulating through the colonnades of the Lyceum.",
    "Mitochondrial dysfunction and oxidative phosphorylation impairment are increasingly implicated in the etiopathogenesis of Parkinson's disease and related synucleinopathies.",
    "The Turing completeness of cellular automata, as demonstrated by Rule 110, establishes that even simple computational systems can simulate arbitrary algorithmic processes.",
    "Cross-linguistic morphosyntactic variation in relative clause formation strategies presents significant challenges for universal grammar theories.",
    "The renormalization group in quantum field theory provides a systematic framework for understanding how physical theories change across different energy scales.",
    "Epigenetic modifications, including DNA methylation and histone acetylation, regulate gene expression without altering the underlying nucleotide sequence.",
    "The archaeological evidence from Göbekli Tepe fundamentally challenges the conventional chronology of the Neolithic Revolution by predating agricultural sedentism.",
    "Microfluidic organ-on-a-chip platforms recapitulate physiologically relevant tissue-tissue interfaces, offering alternatives to animal models in pharmaceutical development.",
    "The cosmological constant problem represents perhaps the most severe fine-tuning issue in theoretical physics, with a discrepancy of approximately 120 orders of magnitude.",
    "Proprioceptive feedback from muscle spindles and Golgi tendon organs is integrated in the cerebellum to produce coordinated voluntary movement and postural stability.",
    "The fiduciary duty of corporate directors to maximize shareholder value has been increasingly challenged by stakeholder-centric models of corporate governance.",
    "Topological quantum computing leverages non-Abelian anyonic excitations in fractional quantum Hall states to achieve inherently fault-tolerant quantum information processing.",
    "The counterfactual definiteness assumption in Bell's theorem is incompatible with the statistical predictions of quantum mechanics, as confirmed by loophole-free experiments.",
    "Dysregulation of the hypothalamic-pituitary-adrenal axis is implicated in the pathophysiology of post-traumatic stress disorder, manifesting as altered cortisol metabolism.",
    "The political economy of international trade agreements involves complex multilateral negotiations balancing protectionist domestic interests against the theoretical gains from comparative advantage.",
    "CRISPR-Cas9 mediated gene editing with homology-directed repair enables precise nucleotide substitutions at targeted genomic loci in eukaryotic organisms.",
    "The phenomenology of temporal consciousness, as analyzed by Husserl's theory of internal time-consciousness, reveals the tripartite structure of retention, primal impression, and protention.",
    "Adversarial examples demonstrate the fragility of deep neural network classifiers, where imperceptible perturbations to input data can cause catastrophic misclassification.",
    "The sedimentary record of Snowball Earth episodes suggests that the entire planet experienced near-complete glaciation during the Neoproterozoic era.",
    "Glomerular filtration rate estimation using the CKD-EPI equation provides superior prognostic accuracy compared to the older Cockcroft-Gault formula in chronic kidney disease staging.",
    "The paradox of tolerance, as articulated by Karl Popper, argues that unlimited tolerance inevitably leads to the disappearance of tolerance itself.",
    "Quantum chromodynamics describes the strong nuclear force through the exchange of gluons between quarks, with the phenomenon of asymptotic freedom at high energies.",
    "The Voynich manuscript remains one of the most enigmatic documents in cryptographic history, with its undeciphered script and mysterious botanical illustrations defying analysis for centuries.",
    "Saccadic suppression during rapid eye movements demonstrates that visual perception is not a continuous process but rather a series of discrete sampling events.",
    "The implementation of cap-and-trade emissions trading schemes requires careful calibration of permit allocation to avoid windfall profits and carbon leakage.",
    "Homotopy type theory provides an alternative foundation for mathematics that unifies constructive type theory with abstract homotopy theory through the univalence axiom.",
    "The pathognomonic Kayser-Fleischer rings observed on slit-lamp examination indicate copper deposition in Descemet's membrane, diagnostic of Wilson's disease.",
    "Blockchain consensus mechanisms must balance the trilemma of decentralization, security, and scalability, with proof-of-stake offering different trade-offs than proof-of-work.",
    "The ontological argument for the existence of God, first formulated by Anselm of Canterbury, proceeds from the concept of a maximally great being to assert its necessary existence.",
    "Interferometric gravitational wave detectors achieve displacement sensitivities of approximately ten to the negative eighteen meters, enabling the observation of binary neutron star mergers.",
    "The dorsal and ventral visual processing streams, corresponding to spatial localization and object identification respectively, demonstrate a functional double dissociation in neuropsychological lesion studies.",
    "Supply chain resilience modeling increasingly employs agent-based simulation to capture emergent systemic risks arising from the nonlinear interactions of heterogeneous economic actors.",
    "The Dirac equation reconciled quantum mechanics with special relativity, predicting the existence of antimatter and establishing the theoretical foundation for quantum electrodynamics.",
    "Telomerase reverse transcriptase activity and its relationship to cellular senescence represents a key area of investigation in both oncology and gerontological research.",
    "The Hausdorff dimension of the Mandelbrot set boundary is exactly two, despite the set itself having a fractal structure with self-similar features at all scales.",
    "Neuroplasticity following stroke involves both perilesional cortical reorganization and contralesional compensatory recruitment, with rehabilitation timing critically influencing functional recovery outcomes.",
    "The geomorphological processes of fluvial erosion and sediment transport are governed by the complex interplay of hydraulic shear stress, grain size distribution, and channel morphology.",
    "Implicit bias, as measured by the Implicit Association Test, reveals automatic cognitive associations that operate independently of conscious attitudes and explicitly held beliefs.",
    "The renin-angiotensin-aldosterone system plays a central role in blood pressure homeostasis, with pharmacological interruption at multiple points forming the basis of antihypertensive therapy.",
    "Gödel's second incompleteness theorem demonstrates that no consistent formal system capable of expressing elementary arithmetic can prove its own consistency.",
    "The stratospheric ozone layer's attenuation of solar ultraviolet radiation is essential for the viability of terrestrial ecosystems, with chlorofluorocarbon-mediated depletion causing significant ecological concern.",
    "Tensor network methods, including matrix product states and projected entangled pair states, provide efficient representations of quantum many-body wavefunctions with limited entanglement.",
    "The vestibulo-ocular reflex maintains retinal image stability during head movements by generating compensatory eye rotations with a latency of approximately ten milliseconds.",
    "Fiscal multiplier estimates vary considerably across economic conditions, with multipliers substantially exceeding unity during periods of monetary policy accommodation at the zero lower bound.",
    "The Krebs cycle, also known as the tricarboxylic acid cycle, represents the central metabolic hub for the oxidative catabolism of carbohydrates, lipids, and amino acids.",
    "Post-structuralist critiques of Enlightenment rationality emphasize the contingency of knowledge claims and the role of power relations in constituting epistemic authority.",
    "The quantum Zeno effect demonstrates that frequent measurement of a quantum system can inhibit its evolution, effectively freezing transitions between quantum states.",
    "Astrocytic calcium signaling through gap junction coupled networks modulates synaptic transmission and neurovascular coupling in ways previously attributed solely to neuronal activity.",
    "The prisoner's dilemma illustrates how individually rational strategies can produce collectively suboptimal outcomes, providing a formal framework for analyzing cooperation and defection in game theory.",
    "Cretaceous amber inclusions preserve arthropod specimens with extraordinary morphological fidelity, enabling phylogenetic analyses spanning approximately one hundred million years of evolutionary history.",
    "The vagus nerve's afferent fibers transmit visceral sensory information to the nucleus tractus solitarius, forming the sensory limb of numerous autonomic reflex arcs.",
    "Monetary policy transmission mechanisms operate through multiple channels including the interest rate channel, credit channel, exchange rate channel, and asset price channel.",
    "The holographic principle suggests that the information content of a region of space is bounded by the area of its boundary surface rather than its volume.",
    "Somatic hypermutation in immunoglobulin variable regions, coupled with clonal selection, drives affinity maturation of the humoral immune response during germinal center reactions.",
    "The archaeological site at Lascaux contains paleolithic cave paintings approximately seventeen thousand years old, representing some of the earliest known examples of figurative art.",
    "Lattice quantum chromodynamics calculations on exascale supercomputers have enabled first-principles predictions of hadron masses with sub-percent accuracy.",
    "The Weber-Fechner law describes the logarithmic relationship between stimulus intensity and perceived magnitude, establishing foundational principles of psychophysics.",
]

CODE_SNIPPETS = [
    "def fibonacci(n): return n if n <= 1 else fibonacci(n-1) + fibonacci(n-2)",
    "SELECT u.name, COUNT(o.id) FROM users u LEFT JOIN orders o ON u.id = o.user_id GROUP BY u.name HAVING COUNT(o.id) > 5;",
    "const fetchData = async (url) => { const res = await fetch(url); return res.json(); };",
    "import numpy as np; arr = np.random.randn(100, 100); eigenvalues = np.linalg.eigvals(arr)",
    "for i in range(len(matrix)): matrix[i][i] = sum(matrix[i]) - matrix[i][i]",
    "CREATE TABLE employees (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, salary DECIMAL(10,2));",
    "document.querySelectorAll('.item').forEach(el => el.addEventListener('click', handleClick));",
    "from collections import defaultdict; graph = defaultdict(list); graph['a'].append(('b', 5))",
    "grep -rn 'TODO\\|FIXME\\|HACK' --include='*.py' src/ | sort -t: -k1,1 -k2,2n",
    "class Node: def __init__(self, val=0, left=None, right=None): self.val, self.left, self.right = val, left, right",
    "SELECT DATE_TRUNC('month', created_at) AS month, SUM(amount) FROM transactions WHERE status = 'completed' GROUP BY 1 ORDER BY 1;",
    "app.get('/api/users/:id', authenticate, async (req, res) => { const user = await User.findById(req.params.id); res.json(user); });",
    "def merge_sort(arr): return arr if len(arr) <= 1 else merge(merge_sort(arr[:len(arr)//2]), merge_sort(arr[len(arr)//2:]))",
    "ALTER TABLE products ADD COLUMN category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL;",
    "const debounce = (fn, ms) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), ms); }; };",
    "with open('data.csv', 'r') as f: reader = csv.DictReader(f); rows = [r for r in reader if float(r['score']) > 0.95]",
    "docker run -d --name postgres -e POSTGRES_PASSWORD=secret -p 5432:5432 -v pgdata:/var/lib/postgresql/data postgres:15",
    "class Meta(type): def __new__(mcs, name, bases, namespace): namespace['registry'] = {}; return super().__new__(mcs, name, bases, namespace)",
    "SELECT p.name, AVG(r.rating) as avg_rating FROM products p JOIN reviews r ON p.id = r.product_id GROUP BY p.id HAVING AVG(r.rating) >= 4.0 ORDER BY avg_rating DESC LIMIT 10;",
    "useEffect(() => { const controller = new AbortController(); fetchData(controller.signal); return () => controller.abort(); }, [dependency]);",
    "lambda x: sorted(x, key=lambda item: (item['priority'], -item['timestamp']))",
    "git log --oneline --graph --all --decorate | head -20",
    "interface ApiResponse<T> { data: T; status: number; error?: string; timestamp: Date; }",
    "def binary_search(arr, target): lo, hi = 0, len(arr)-1; return -1 if lo > hi else ...",
    "INSERT INTO audit_log (user_id, action, details, ip_address) VALUES ($1, $2, $3, $4) RETURNING id, created_at;",
    "const pipeline = (...fns) => (x) => fns.reduce((acc, fn) => fn(acc), x);",
    "try: result = requests.get(url, timeout=30); result.raise_for_status() except requests.RequestException as e: logger.error(f'Failed: {e}')",
    "kubectl get pods -n production -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\\n'",
    "@dataclass(frozen=True) class Point: x: float; y: float; def distance(self, other): return ((self.x-other.x)**2 + (self.y-other.y)**2)**0.5",
    "WITH RECURSIVE cte AS (SELECT id, parent_id, name, 1 AS depth FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, c.parent_id, c.name, cte.depth + 1 FROM categories c JOIN cte ON c.parent_id = cte.id) SELECT * FROM cte;",
    "export default function middleware(req: NextRequest) { if (!req.cookies.get('session')) return NextResponse.redirect('/login'); }",
    "async def websocket_handler(websocket): async for message in websocket: data = json.loads(message); await process(data)",
    "SELECT PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY response_time) as p95 FROM api_metrics WHERE endpoint = '/api/search';",
    "const observer = new IntersectionObserver((entries) => entries.forEach(e => e.isIntersecting && loadMore()), { threshold: 0.5 });",
    "def lru_cache_decorator(maxsize=128): cache = OrderedDict(); def decorator(func): ...",
    "EXPLAIN ANALYZE SELECT * FROM events WHERE created_at BETWEEN '2024-01-01' AND '2024-12-31' AND type IN ('click', 'view') ORDER BY created_at DESC;",
    "type Result<T, E = Error> = { success: true; data: T } | { success: false; error: E };",
    "from contextlib import asynccontextmanager; @asynccontextmanager async def db_session(): session = await create_session(); try: yield session; await session.commit() except: await session.rollback(); raise finally: await session.close()",
    "terraform plan -var-file=production.tfvars -out=plan.out && terraform apply plan.out",
    "class Singleton: _instance = None; def __new__(cls): cls._instance = cls._instance or super().__new__(cls); return cls._instance",
    "SELECT json_agg(json_build_object('id', id, 'name', name, 'tags', tags)) FROM items WHERE tags && ARRAY['urgent', 'high-priority'];",
    "Promise.allSettled([fetchUsers(), fetchOrders(), fetchProducts()]).then(results => results.filter(r => r.status === 'fulfilled').map(r => r.value));",
    "def quicksort(arr): pivot = arr[len(arr)//2]; return quicksort([x for x in arr if x < pivot]) + [x for x in arr if x == pivot] + quicksort([x for x in arr if x > pivot]) if arr else []",
    "UPDATE accounts SET balance = balance - 100 WHERE id = 1 AND balance >= 100 RETURNING balance;",
    "const worker = new Worker('./processor.js'); worker.postMessage({ type: 'PROCESS', data: largeArray }); worker.onmessage = (e) => console.log(e.data);",
    "import asyncio; tasks = [asyncio.create_task(fetch(url)) for url in urls]; results = await asyncio.gather(*tasks, return_exceptions=True)",
    "find . -name '*.log' -mtime +30 -exec gzip {} \\; -exec mv {}.gz /archive/ \\;",
    "@pytest.mark.parametrize('input,expected', [(1,1),(2,1),(5,5),(10,55)]) def test_fib(input, expected): assert fibonacci(input) == expected",
    "SELECT COALESCE(SUM(CASE WHEN status = 'active' THEN 1 ELSE 0 END), 0) as active_count, COUNT(*) as total FROM subscriptions WHERE plan_id = $1;",
    "function* range(start, end, step = 1) { for (let i = start; i < end; i += step) yield i; }",
    "class AbstractRepository(ABC): @abstractmethod async def get(self, id: str) -> Optional[Entity]: ...; @abstractmethod async def save(self, entity: Entity) -> None: ...",
    "SELECT e.name, d.name as department, RANK() OVER (PARTITION BY d.id ORDER BY e.salary DESC) as salary_rank FROM employees e JOIN departments d ON e.dept_id = d.id;",
    "const memoize = (fn) => { const cache = new Map(); return (...args) => { const key = JSON.stringify(args); if (!cache.has(key)) cache.set(key, fn(...args)); return cache.get(key); }; };",
    "awk '{sum += $NF; count++} END {printf \"Average: %.2f\\n\", sum/count}' access.log",
    "def flatten(nested): return [item for sublist in nested for item in (flatten(sublist) if isinstance(sublist, list) else [sublist])]",
    "CREATE INDEX CONCURRENTLY idx_events_created_type ON events (created_at DESC, type) WHERE deleted_at IS NULL;",
    "import { z } from 'zod'; const UserSchema = z.object({ name: z.string().min(1), email: z.string().email(), age: z.number().int().positive().optional() });",
    "sed -i 's/oldFunction/newFunction/g' $(grep -rl 'oldFunction' src/ --include='*.ts')",
    "async with aiohttp.ClientSession() as session: async with session.get(url, headers=headers) as resp: data = await resp.json()",
    "SELECT generate_series('2024-01-01'::date, '2024-12-31'::date, '1 day'::interval)::date as date;",
    "const deepClone = <T>(obj: T): T => JSON.parse(JSON.stringify(obj));",
    "from typing import Protocol; class Comparable(Protocol): def __lt__(self, other: Self) -> bool: ...",
    "SELECT EXTRACT(EPOCH FROM NOW() - pg_stat_activity.query_start) AS duration, query FROM pg_stat_activity WHERE state = 'active' AND query NOT ILIKE '%pg_stat%' ORDER BY duration DESC;",
    "router.use((err: Error, req: Request, res: Response, next: NextFunction) => { logger.error(err.stack); res.status(500).json({ error: 'Internal Server Error' }); });",
    "def thread_pool_map(func, items, max_workers=8): with ThreadPoolExecutor(max_workers=max_workers) as executor: return list(executor.map(func, items))",
    "COPY (SELECT * FROM large_table WHERE created_at >= CURRENT_DATE - INTERVAL '7 days') TO '/tmp/export.csv' WITH CSV HEADER;",
    "const retry = async (fn, retries = 3, delay = 1000) => { try { return await fn(); } catch (e) { if (retries <= 0) throw e; await new Promise(r => setTimeout(r, delay)); return retry(fn, retries - 1, delay * 2); } };",
    "class EventEmitter: def __init__(self): self._listeners = defaultdict(list); def on(self, event, fn): self._listeners[event].append(fn); def emit(self, event, *args): [fn(*args) for fn in self._listeners[event]]",
    "SELECT table_name, pg_size_pretty(pg_total_relation_size(quote_ident(table_name))) FROM information_schema.tables WHERE table_schema = 'public' ORDER BY pg_total_relation_size(quote_ident(table_name)) DESC;",
    "const groupBy = <T>(arr: T[], key: keyof T): Record<string, T[]> => arr.reduce((acc, item) => ({ ...acc, [String(item[key])]: [...(acc[String(item[key])] || []), item] }), {} as Record<string, T[]>);",
    "jq '.[] | select(.status == \"error\") | {name: .name, msg: .error.message}' results.json | head -20",
    "def cached_property(func): attr = f'_cached_{func.__name__}'; @property @wraps(func) def wrapper(self): if not hasattr(self, attr): setattr(self, attr, func(self)); return getattr(self, attr); return wrapper",
    "WITH monthly AS (SELECT DATE_TRUNC('month', date) AS month, SUM(revenue) AS rev FROM sales GROUP BY 1) SELECT month, rev, LAG(rev) OVER (ORDER BY month) AS prev, ROUND((rev - LAG(rev) OVER (ORDER BY month)) / LAG(rev) OVER (ORDER BY month) * 100, 2) AS growth_pct FROM monthly;",
    "addEventListener('fetch', event => event.respondWith(caches.match(event.request).then(r => r || fetch(event.request).then(resp => { caches.open('v1').then(c => c.put(event.request, resp.clone())); return resp; }))));",
    "def topological_sort(graph): visited, stack = set(), []; def dfs(node): visited.add(node); [dfs(n) for n in graph.get(node, []) if n not in visited]; stack.append(node); [dfs(n) for n in graph if n not in visited]; return stack[::-1]",
    "xargs -I {} -P 4 sh -c 'curl -s \"https://api.example.com/items/{}\" | jq .name' < ids.txt",
    "SELECT id, name, CASE WHEN score >= 90 THEN 'A' WHEN score >= 80 THEN 'B' WHEN score >= 70 THEN 'C' ELSE 'F' END AS grade FROM students ORDER BY score DESC;",
    "new Proxy(target, { get(obj, prop) { console.log(`Accessing ${String(prop)}`); return Reflect.get(obj, prop); }, set(obj, prop, val) { console.log(`Setting ${String(prop)} = ${val}`); return Reflect.set(obj, prop, val); } });",
    "from functools import reduce; compose = lambda *fns: reduce(lambda f, g: lambda x: f(g(x)), fns)",
    "VACUUM (VERBOSE, ANALYZE) large_table;",
    "rsync -avz --progress --exclude='node_modules' --exclude='.git' ./src/ user@server:/deploy/",
    "class Graph: def dijkstra(self, start): dist = {start: 0}; pq = [(0, start)]; while pq: d, u = heapq.heappop(pq); ...",
    "SELECT DISTINCT ON (user_id) user_id, action, created_at FROM user_actions ORDER BY user_id, created_at DESC;",
    "const zip = <T, U>(a: T[], b: U[]): [T, U][] => a.map((val, i) => [val, b[i]]);",
    "import re; tokens = re.findall(r'\\b\\w+\\b|[^\\w\\s]', text.lower()); freq = Counter(tokens).most_common(20)",
    "pg_dump --format=custom --compress=9 --jobs=4 --file=backup.dump production_db",
    "class Vector: def __init__(self, *components): self.components = components; def __add__(self, other): return Vector(*(a+b for a,b in zip(self.components, other.components)))",
    "SELECT w.word, COUNT(*) as freq, ROUND(COUNT(*)::numeric / SUM(COUNT(*)) OVER () * 100, 4) as pct FROM words w GROUP BY w.word ORDER BY freq DESC LIMIT 100;",
    "const chunk = <T>(arr: T[], size: number): T[][] => Array.from({ length: Math.ceil(arr.length / size) }, (_, i) => arr.slice(i * size, i * size + size));",
    "#!/bin/bash\nset -euo pipefail\nfor f in *.json; do echo \"Processing $f\"; jq -c '.data[]' \"$f\" >> combined.jsonl; done",
    "def matrix_multiply(A, B): return [[sum(a*b for a,b in zip(row,col)) for col in zip(*B)] for row in A]",
    "GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO readonly_user; ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_user;",
    "const throttle = (fn: Function, limit: number) => { let inThrottle = false; return function(this: any, ...args: any[]) { if (!inThrottle) { fn.apply(this, args); inThrottle = true; setTimeout(() => inThrottle = false, limit); } }; };",
]

MATHEMATICAL = [
    "The integral of e^(-x^2) from negative infinity to positive infinity equals the square root of pi.",
    "If f(x) = x^3 - 3x^2 + 2x, then f'(x) = 3x^2 - 6x + 2 and f''(x) = 6x - 6.",
    "The eigenvalues of the matrix [[2, 1], [1, 2]] are lambda_1 = 3 and lambda_2 = 1.",
    "Euler's identity: e^(i*pi) + 1 = 0 connects five fundamental mathematical constants.",
    "The Taylor series expansion of sin(x) = x - x^3/3! + x^5/5! - x^7/7! + ...",
    "For a 95% confidence interval: x_bar +/- 1.96 * (sigma / sqrt(n))",
    "The determinant of a 3x3 matrix: det(A) = a(ei-fh) - b(di-fg) + c(dh-eg)",
    "Bayes' theorem: P(A|B) = P(B|A) * P(A) / P(B) where P(B) != 0",
    "The quadratic formula: x = (-b +/- sqrt(b^2 - 4ac)) / (2a)",
    "sum_{k=1}^{n} k^2 = n(n+1)(2n+1)/6",
    "The Fibonacci sequence satisfies F(n) = F(n-1) + F(n-2) with F(0) = 0, F(1) = 1.",
    "lim_{x->0} sin(x)/x = 1, a fundamental limit in calculus.",
    "The gradient of f(x,y) = x^2*y + y^3 is nabla_f = (2xy, x^2 + 3y^2).",
    "The divergence theorem: integral_V (div F) dV = integral_S F . dS",
    "Stirling's approximation: n! ~ sqrt(2*pi*n) * (n/e)^n for large n.",
    "The Cauchy-Schwarz inequality: |<u,v>|^2 <= <u,u> * <v,v>",
    "The Laplace transform of f(t) = e^(at) is F(s) = 1/(s-a) for s > a.",
    "A geometric series: sum_{k=0}^{inf} r^k = 1/(1-r) for |r| < 1.",
    "The cross product: a x b = |i  j  k; a1 a2 a3; b1 b2 b3|",
    "The binomial coefficient C(n,k) = n! / (k! * (n-k)!)",
    "The chain rule: d/dx[f(g(x))] = f'(g(x)) * g'(x)",
    "The area of an ellipse with semi-axes a and b is A = pi * a * b.",
    "The Fourier transform: F(w) = integral_{-inf}^{inf} f(t) * e^(-iwt) dt",
    "log_b(x*y) = log_b(x) + log_b(y) and log_b(x/y) = log_b(x) - log_b(y)",
    "The moment of inertia of a solid sphere: I = (2/5) * m * r^2",
    "Green's theorem: integral_C (P dx + Q dy) = integral_D (dQ/dx - dP/dy) dA",
    "The variance: Var(X) = E[X^2] - (E[X])^2 = sum (x_i - mu)^2 / n",
    "Euler's formula for polyhedra: V - E + F = 2 where V=vertices, E=edges, F=faces.",
    "The normal distribution: f(x) = (1 / (sigma * sqrt(2*pi))) * e^(-(x-mu)^2 / (2*sigma^2))",
    "The Pythagorean theorem in n dimensions: |v| = sqrt(v1^2 + v2^2 + ... + vn^2)",
    "Integration by parts: integral u dv = uv - integral v du",
    "The Maclaurin series for e^x = 1 + x + x^2/2! + x^3/3! + ...",
    "The Jacobian matrix J_{ij} = partial(f_i)/partial(x_j) transforms between coordinate systems.",
    "The Poisson distribution: P(X=k) = (lambda^k * e^(-lambda)) / k!",
    "Newton's method: x_{n+1} = x_n - f(x_n) / f'(x_n)",
    "The trace of a matrix equals the sum of its eigenvalues: tr(A) = sum(lambda_i).",
    "Stokes' theorem: integral_S (curl F) . dS = integral_C F . dr",
    "The arithmetic-geometric mean inequality: (a+b)/2 >= sqrt(ab) for a,b >= 0.",
    "The Riemann sum: integral_a^b f(x) dx = lim_{n->inf} sum_{i=1}^{n} f(x_i*) * Delta_x",
    "Cramer's rule: x_i = det(A_i) / det(A) where A_i replaces column i with b.",
    "The gamma function: Gamma(n) = (n-1)! for positive integers, and Gamma(1/2) = sqrt(pi).",
    "The convolution: (f * g)(t) = integral_{-inf}^{inf} f(tau) * g(t - tau) d_tau",
    "L'Hôpital's rule: if lim f/g = 0/0 or inf/inf, then lim f/g = lim f'/g'.",
    "The distance formula: d = sqrt((x2-x1)^2 + (y2-y1)^2 + (z2-z1)^2)",
    "The beta function: B(a,b) = integral_0^1 t^(a-1) * (1-t)^(b-1) dt = Gamma(a)*Gamma(b)/Gamma(a+b)",
    "A matrix is positive definite iff all eigenvalues are positive: x^T A x > 0 for all x != 0.",
    "The Legendre polynomials satisfy: (1-x^2)P_n''(x) - 2xP_n'(x) + n(n+1)P_n(x) = 0",
    "The Z-transform: X(z) = sum_{n=-inf}^{inf} x[n] * z^(-n)",
    "The law of cosines: c^2 = a^2 + b^2 - 2ab*cos(C)",
    "The Wronskian: W(f,g) = f*g' - f'*g determines linear independence of solutions.",
    "Euler's totient function: phi(n) = n * product_{p|n} (1 - 1/p) for prime factors p.",
    "The residue theorem: integral_C f(z) dz = 2*pi*i * sum Res(f, z_k)",
    "The Schwarz inequality for integrals: |integral fg|^2 <= integral |f|^2 * integral |g|^2",
    "The Dirichlet series: sum_{n=1}^{inf} a_n / n^s converges for Re(s) > sigma_c.",
    "The power series radius of convergence: R = 1 / limsup |a_n|^(1/n)",
    "The Catalan numbers: C_n = C(2n,n) / (n+1) = (2n)! / ((n+1)! * n!)",
    "The p-norm: ||x||_p = (sum |x_i|^p)^(1/p) with ||x||_inf = max|x_i|",
    "The Vandermonde determinant: det(V) = product_{i<j} (x_j - x_i)",
    "The characteristic polynomial: det(A - lambda*I) = 0 gives eigenvalues.",
    "Parseval's theorem: sum |a_n|^2 = (1/T) * integral_0^T |f(t)|^2 dt",
    "The Bernoulli numbers satisfy: sum_{k=0}^{n} C(n+1,k) * B_k = 0 for n >= 1.",
    "The spectral radius: rho(A) = max |lambda_i| determines convergence of iterative methods.",
    "The Lagrange multiplier condition: nabla_f = lambda * nabla_g at constrained extrema.",
    "The sinh and cosh identities: cosh^2(x) - sinh^2(x) = 1",
    "The Jordan normal form: any matrix is similar to a block diagonal of Jordan blocks.",
    "The Hermite polynomials: H_n(x) = (-1)^n * e^(x^2) * d^n/dx^n(e^(-x^2))",
    "Simpson's rule: integral_a^b f(x)dx ≈ (h/3)[f(a) + 4f(a+h) + 2f(a+2h) + ... + f(b)]",
    "The multinomial theorem: (x1+...+xm)^n = sum n!/(k1!...km!) * x1^k1 * ... * xm^km",
    "The Gauss-Bonnet theorem: integral_M K dA + integral_{dM} k_g ds = 2*pi*chi(M)",
    "The matrix exponential: e^(At) = sum_{k=0}^{inf} (At)^k / k! solves x' = Ax.",
    "Goldbach's conjecture: every even integer greater than 2 is the sum of two primes.",
    "The Minkowski inequality: ||f+g||_p <= ||f||_p + ||g||_p for p >= 1.",
    "The discrete Fourier transform: X_k = sum_{n=0}^{N-1} x_n * e^(-2*pi*i*k*n/N)",
    "The Hessian matrix H_{ij} = d^2f/(dx_i*dx_j) determines local curvature.",
    "A Mersenne prime has the form 2^p - 1 where p itself is prime.",
    "The central limit theorem: (X_bar - mu) / (sigma/sqrt(n)) -> N(0,1) as n -> inf.",
    "The Abel summation formula: sum a_n b_n = A_N b_N - sum A_n (b_{n+1} - b_n).",
    "The Hölder inequality: sum |x_i*y_i| <= (sum |x_i|^p)^(1/p) * (sum |y_i|^q)^(1/q) where 1/p+1/q=1.",
    "The Chebyshev inequality: P(|X-mu| >= k*sigma) <= 1/k^2 for any k > 0.",
    "The rotation matrix in 2D: R(theta) = [[cos(theta), -sin(theta)], [sin(theta), cos(theta)]].",
    "The partial fraction decomposition: 1/((x-a)(x-b)) = (1/(a-b)) * (1/(x-a) - 1/(x-b)).",
    "The Leibniz formula for pi: pi/4 = 1 - 1/3 + 1/5 - 1/7 + ...",
    "The Fibonacci closed form: F(n) = (phi^n - psi^n) / sqrt(5) where phi = (1+sqrt(5))/2.",
    "The Ramanujan sum: 1+2+3+... = -1/12 under zeta function regularization.",
    "The SVD decomposition: A = U*Sigma*V^T where U,V are orthogonal and Sigma is diagonal.",
    "Fermat's little theorem: a^(p-1) ≡ 1 (mod p) for prime p and gcd(a,p) = 1.",
    "The Euler-Lagrange equation: d/dt(dL/dq') - dL/dq = 0 for variational problems.",
    "The Chinese remainder theorem: if gcd(m,n)=1 then Z/(mn) ≅ Z/m × Z/n.",
    "The logistic map: x_{n+1} = r*x_n*(1-x_n) exhibits chaos for r > 3.57.",
    "The Wallis product: pi/2 = product_{n=1}^{inf} (4n^2)/(4n^2-1).",
    "The rank-nullity theorem: rank(A) + nullity(A) = number of columns of A.",
    "The Rodrigues formula for Legendre polynomials: P_n(x) = (1/(2^n*n!)) * d^n/dx^n[(x^2-1)^n].",
    "The KL divergence: D_KL(P||Q) = sum P(x) * log(P(x)/Q(x)) >= 0.",
    "The Euler product for zeta: zeta(s) = product_{p prime} 1/(1-p^(-s)) for Re(s) > 1.",
    "The isoperimetric inequality: 4*pi*A <= L^2 with equality for circles.",
    "The Weierstrass approximation theorem: continuous functions on [a,b] are uniformly approximable by polynomials.",
    "The Lucas numbers: L(n) = L(n-1) + L(n-2) with L(0)=2, L(1)=1.",
]

CJK_SENTENCES = [
    "今天的天气非常好，我们一起去公园散步吧。",
    "这家餐厅的红烧肉做得特别好吃。",
    "人工智能技术正在改变我们的生活方式。",
    "春天来了，樱花开满了整条街道。",
    "他每天早上六点起床跑步锻炼身体。",
    "这本书讲述了一个关于勇气和友情的故事。",
    "中国的长城是世界上最伟大的建筑之一。",
    "学习一门新语言需要持续的努力和耐心。",
    "深度学习在图像识别领域取得了突破性进展。",
    "我们应该珍惜和家人在一起的每一刻时光。",
    "量子计算将会彻底改变密码学和药物研发领域。",
    "北京的故宫博物院收藏了大量珍贵的历史文物。",
    "随着城市化的发展，交通拥堵问题日益严重。",
    "太空探索是人类追求知识和冒险精神的体现。",
    "传统中医药在现代医学中仍然发挥着重要作用。",
    "今年的高考数学试卷难度比往年有所增加。",
    "全球变暖导致了极端天气事件的频率增加。",
    "上海是中国最大的经济中心和国际金融城市。",
    "科学家们正在研究如何利用核聚变产生清洁能源。",
    "这部电影获得了今年奥斯卡最佳影片奖的提名。",
    "今日は天気がとても良いので、公園に散歩に行きましょう。",
    "東京タワーから見る夜景はとても美しいです。",
    "日本の伝統的な茶道は心の平和を追求する文化です。",
    "新幹線は日本の高速鉄道技術の象徴です。",
    "桜の季節になると、多くの人がお花見を楽しみます。",
    "この問題を解決するためには、新しいアプローチが必要です。",
    "人工知能の発展は社会に大きな影響を与えています。",
    "京都には数多くの歴史的な寺院や神社があります。",
    "日本語の敬語は非常に複雑で、使い分けが難しいです。",
    "最新の研究によると、睡眠は記憶の定着に重要な役割を果たしています。",
    "机器学习模型的训练需要大量的标注数据和计算资源。",
    "自然语言处理是人工智能领域中最具挑战性的任务之一。",
    "区块链技术的去中心化特性使其在金融领域具有广泛的应用前景。",
    "可持续发展已经成为全球经济发展的核心议题。",
    "神经网络的反向传播算法是深度学习的基础。",
    "中国的高铁网络已经成为世界上最大的高速铁路系统。",
    "大数据分析技术正在帮助企业做出更加精准的决策。",
    "气候变化对全球生态系统构成了严重威胁。",
    "半导体产业链的全球化分工面临着地缘政治的挑战。",
    "基因编辑技术CRISPR的发现开启了生物医学的新纪元。",
    "彼は毎朝ジョギングをして健康を維持しています。",
    "ロボット工学の進歩は製造業に革命をもたらしています。",
    "富士山は日本で最も高い山で、標高は三千七百七十六メートルです。",
    "量子コンピュータの実用化にはまだ多くの技術的課題があります。",
    "日本の食文化は世界無形文化遺産に登録されています。",
    "环境保护和经济发展之间需要找到平衡点。",
    "人工智能在医疗诊断中的应用越来越广泛。",
    "云计算技术使得企业能够灵活地扩展其IT基础设施。",
    "数字货币的出现正在重塑全球金融体系。",
    "光子芯片的研发将推动下一代计算技术的发展。",
    "歴史は繰り返すと言われますが、同じ過ちを犯さないことが大切です。",
    "プログラミング教育は子供たちの論理的思考力を養います。",
    "和食は栄養バランスが良く、世界中で人気があります。",
    "このソフトウェアのアップデートにより、セキュリティが大幅に向上しました。",
    "日本の漫画やアニメは世界中のファンに愛されています。",
    "知识图谱技术在搜索引擎和推荐系统中发挥着重要作用。",
    "联邦学习是一种保护隐私的分布式机器学习方法。",
    "新能源汽车的普及将有助于减少碳排放。",
    "强化学习算法在游戏和机器人控制中取得了显著成就。",
    "物联网技术正在推动智慧城市的建设和发展。",
    "相対性理論はアインシュタインによって提唱された物理学の基本理論です。",
    "日本の四季折々の風景は多くの観光客を魅了しています。",
    "持続可能なエネルギー源の開発は世界的な課題です。",
    "北海道のラベンダー畑は夏になると紫色の絨毯のように広がります。",
    "デジタルトランスフォーメーションは企業の競争力を高める鍵です。",
    "自动驾驶技术的发展需要解决安全性和法律法规等多方面的问题。",
    "蛋白质折叠问题是生物学中最重要的未解之谜之一。",
    "超级计算机在天气预报和气候模拟中发挥着关键作用。",
    "社交媒体平台对公众舆论的形成产生了深远的影响。",
    "量子纠缠现象挑战了我们对物理世界的传统认知。",
    "テクノロジーの進化は人々の働き方を大きく変えています。",
    "日本の新幹線は世界で最も安全な交通手段の一つです。",
    "人間の脳の仕組みを理解することは、人工知能の発展に不可欠です。",
    "再生可能エネルギーの利用拡大は温室効果ガス削減に貢献します。",
    "古代シルクロードは東西文明の交流を促進しました。",
    "计算机视觉技术在安防监控和自动驾驶中有着广泛的应用。",
    "边缘计算将数据处理从云端移到了靠近数据源的位置。",
    "碳中和目标要求各国大幅减少化石燃料的使用。",
    "脑机接口技术有望帮助瘫痪患者恢复运动能力。",
    "大语言模型的涌现能力引发了学术界的广泛讨论。",
    "先端医療技術の発展は平均寿命の延伸に大きく貢献しています。",
    "データサイエンスは現代のビジネスにおいて不可欠なスキルです。",
    "日本の伝統工芸品は職人の技と美意識の結晶です。",
    "サイバーセキュリティの重要性は年々増加しています。",
    "宇宙ステーションでの実験は地上では不可能な研究を可能にします。",
    "多模态人工智能能够同时处理文本、图像和音频等多种类型的数据。",
    "拓扑量子计算利用任意子的编织操作来实现容错量子计算。",
    "合成生物学正在开创设计和构建新型生物系统的可能性。",
    "元宇宙概念的兴起引发了人们对虚拟现实未来的无限想象。",
    "纳米技术在材料科学和医学领域展现出了巨大的应用潜力。",
    "気候変動に対する国際的な協力体制の構築が急務です。",
    "バイオテクノロジーの進歩は農業と医療に革命をもたらしています。",
    "日本の精密機械産業は世界最高水準の技術力を誇っています。",
    "自然言語処理技術の発展により、機械翻訳の精度が大幅に向上しました。",
    "宇宙探査は人類の好奇心と探究心の象徴です。",
    "可解释人工智能旨在使机器学习模型的决策过程更加透明。",
    "数字孪生技术通过虚拟模型来模拟和优化实体系统的运行。",
    "光量子计算机利用光子作为量子比特来进行量子信息处理。",
    "生成式人工智能正在深刻改变内容创作和知识工作的方式。",
    "异构计算架构结合了CPU、GPU和专用加速器的优势。",
]

MULTILINGUAL = [
    "Le petit prince est un livre merveilleux qui parle d'amitié et de responsabilité.",
    "Die Quantenmechanik beschreibt das Verhalten von Teilchen auf subatomarer Ebene.",
    "Los algoritmos de aprendizaje profundo han revolucionado el procesamiento de imágenes.",
    "الذكاء الاصطناعي يغير طريقة تفاعلنا مع التكنولوجيا بشكل جذري",
    "कृत्रिम बुद्धिमत्ता ने प्रौद्योगिकी के क्षेत्र में क्रांति ला दी है।",
    "La tour Eiffel est le monument le plus visité au monde avec près de sept millions de visiteurs par an.",
    "Die Relativitätstheorie von Einstein hat unser Verständnis von Raum und Zeit grundlegend verändert.",
    "El cambio climático representa uno de los mayores desafíos de nuestra generación.",
    "يعتبر تعلم الآلة من أهم فروع الذكاء الاصطناعي في العصر الحديث",
    "भारत में सूचना प्रौद्योगिकी उद्योग ने पिछले दो दशकों में अभूतपूर्व विकास किया है।",
    "Les réseaux de neurones artificiels sont inspirés du fonctionnement du cerveau humain.",
    "Die Blockchain-Technologie ermöglicht dezentralisierte und transparente Transaktionen ohne Zwischenhändler.",
    "La inteligencia artificial está transformando la manera en que diagnosticamos enfermedades.",
    "تطبيقات الحوسبة السحابية أصبحت جزءاً أساسياً من البنية التحتية الرقمية",
    "गहन शिक्षण एल्गोरिदम ने छवि पहचान और प्राकृतिक भाषा प्रसंस्करण में उल्लेखनीय प्रगति की है।",
    "La gastronomie française est inscrite au patrimoine culturel immatériel de l'UNESCO.",
    "Maschinelles Lernen ist ein Teilgebiet der künstlichen Intelligenz, das Computern ermöglicht, aus Daten zu lernen.",
    "Las energías renovables son fundamentales para combatir el calentamiento global.",
    "البرمجة هي لغة المستقبل ويجب على الجميع تعلم أساسياتها",
    "क्वांटम कंप्यूटिंग पारंपरिक कंप्यूटरों की तुलना में कुछ समस्याओं को तेजी से हल कर सकती है।",
    "L'apprentissage par renforcement permet aux agents d'apprendre des stratégies optimales par essai et erreur.",
    "Das Periodensystem der Elemente ordnet alle bekannten chemischen Elemente nach ihrer Ordnungszahl.",
    "La computación cuántica promete resolver problemas que son intratables para las computadoras clásicas.",
    "الروبوتات الذكية ستلعب دوراً محورياً في مستقبل الصناعة والخدمات",
    "नैनो प्रौद्योगिकी ने चिकित्सा और सामग्री विज्ञान में नए अवसर खोले हैं।",
    "Les véhicules autonomes utilisent des capteurs lidar et des algorithmes de vision par ordinateur.",
    "Quantencomputer nutzen die Prinzipien der Quantenmechanik für leistungsfähigere Berechnungen.",
    "El procesamiento del lenguaje natural permite a las máquinas entender y generar texto humano.",
    "الحوسبة الكمومية ستحدث ثورة في مجال التشفير وأمن المعلومات",
    "जलवायु परिवर्तन से निपटने के लिए वैश्विक सहयोग अत्यंत आवश्यक है।",
    "La cryptographie quantique offre une sécurité théoriquement inviolable pour les communications.",
    "Erneuerbare Energien wie Solar- und Windkraft sind entscheidend für die Energiewende.",
    "Los modelos de lenguaje grande han demostrado capacidades emergentes sorprendentes.",
    "الشبكات العصبية العميقة تحقق نتائج مذهلة في التعرف على الأنماط",
    "भारतीय अंतरिक्ष अनुसंधान संगठन ने चंद्रयान मिशन से विश्व में अपनी पहचान बनाई है।",
    "Le traitement automatique du langage naturel est essentiel pour les assistants virtuels.",
    "Die Gentechnik eröffnet neue Möglichkeiten in der Medizin und Landwirtschaft.",
    "La biotecnología está abriendo nuevas fronteras en la medicina personalizada.",
    "تحليل البيانات الضخمة يساعد الشركات في اتخاذ قرارات أفضل",
    "स्वचालित वाहन प्रौद्योगिकी परिवहन के भविष्य को बदलने की क्षमता रखती है।",
    "L'informatique quantique pourrait révolutionner la découverte de médicaments et la science des matériaux.",
    "Künstliche neuronale Netze werden in der Bildverarbeitung und Spracherkennung eingesetzt.",
    "La realidad aumentada combina elementos virtuales con el mundo real para crear experiencias inmersivas.",
    "الطاقة المتجددة هي المفتاح لمستقبل مستدام وصديق للبيئة",
    "संस्कृत भाषा विश्व की सबसे प्राचीन भाषाओं में से एक है और कई आधुनिक भाषाओं की जननी है।",
    "La France est reconnue pour son excellence dans l'aérospatiale et l'industrie nucléaire.",
    "Der digitale Wandel stellt Unternehmen vor neue Herausforderungen und Chancen.",
    "Los semiconductores son la base de toda la electrónica moderna y la computación.",
    "إنترنت الأشياء يربط الأجهزة الذكية ببعضها لتحسين كفاءة الحياة اليومية",
    "मशीन लर्निंग मॉडल को प्रशिक्षित करने के लिए बड़ी मात्रा में डेटा की आवश्यकता होती है।",
    "Les avancées en neurosciences computationnelles éclairent notre compréhension du cerveau.",
    "Die Kernfusion könnte eine nahezu unbegrenzte Energiequelle darstellen, wenn die technischen Hürden überwunden werden.",
    "La ciberseguridad es cada vez más importante en un mundo cada vez más digitalizado.",
    "التعلم العميق هو أحد أكثر مجالات الذكاء الاصطناعي تطوراً في السنوات الأخيرة",
    "हिंदी भारत की राजभाषा है और दुनिया में सबसे अधिक बोली जाने वाली भाषाओं में से एक है।",
    "La modélisation climatique repose sur des simulations numériques complexes exécutées sur des supercalculateurs.",
    "Autonome Systeme werden in der Logistik, Landwirtschaft und im Gesundheitswesen eingesetzt.",
    "El telescopio James Webb está revelando secretos del universo nunca antes observados.",
    "الذكاء الاصطناعي التوليدي يفتح آفاقاً جديدة في الإبداع والتصميم",
    "डिजिटल भारत अभियान ने देश में डिजिटल साक्षरता और इंटरनेट पहुंच को बढ़ावा दिया है।",
    "Jouer de la musique améliore les capacités cognitives et la mémoire.",
    "Naturwissenschaftliche Grundlagenforschung bildet das Fundament für technologische Innovationen.",
    "La exploración espacial nos ayuda a comprender mejor nuestro lugar en el universo.",
    "التحول الرقمي يعيد تشكيل جميع القطاعات الاقتصادية والاجتماعية",
    "आयुर्वेद भारतीय चिकित्सा पद्धति है जो हजारों वर्षों से प्रचलित है।",
    "L'énergie solaire photovoltaïque a vu son coût diminuer de plus de quatre-vingt-dix pour cent en une décennie.",
    "Die Quantenverschränkung ist ein faszinierendes Phänomen, das Einstein als spukhafte Fernwirkung bezeichnete.",
    "Las redes generativas adversariales pueden crear imágenes fotorrealistas de personas que no existen.",
    "الحوسبة الحافية تنقل معالجة البيانات إلى مكان أقرب من مصدر البيانات",
    "योग और ध्यान भारतीय संस्कृति की अमूल्य देन हैं जो विश्वभर में लोकप्रिय हो रहे हैं।",
    "La biodiversité est essentielle au maintien des écosystèmes et au bien-être humain.",
    "Sprachmodelle auf Basis von Transformern haben die natürliche Sprachverarbeitung revolutioniert.",
    "La nanotecnología tiene aplicaciones prometedoras en medicina, energía y ciencia de materiales.",
    "علم الجينوم يكشف أسرار الحمض النووي ويمهد الطريق للطب الشخصي",
    "भारतीय गणित की परंपरा बहुत समृद्ध है, शून्य की खोज से लेकर रामानुजन के सूत्रों तक।",
    "Le métavers représente la prochaine évolution majeure de l'interaction numérique.",
    "Nachhaltige Entwicklung erfordert ein Gleichgewicht zwischen ökonomischen, ökologischen und sozialen Zielen.",
    "La fusión nuclear podría proporcionar una fuente de energía limpia y prácticamente ilimitada.",
    "تقنيات الواقع المعزز والواقع الافتراضي تغير طريقة التعليم والتدريب",
    "कंप्यूटर विज्ञान और गणित आधुनिक प्रौद्योगिकी की नींव हैं।",
    "Les jumeaux numériques permettent de simuler et d'optimiser des systèmes complexes en temps réel.",
    "Photonische Schaltkreise könnten die nächste Generation von ultraschnellen Computern ermöglichen.",
    "El aprendizaje automático federado permite entrenar modelos sin compartir datos sensibles.",
    "الطباعة ثلاثية الأبعاد تحدث ثورة في التصنيع والهندسة المعمارية",
    "सतत विकास लक्ष्यों को प्राप्त करने के लिए सभी देशों को मिलकर काम करना होगा।",
    "La théorie des cordes tente d'unifier la mécanique quantique et la relativité générale.",
    "Wasserstoff als Energieträger spielt eine wichtige Rolle in der Dekarbonisierung der Industrie.",
    "Las ciudades inteligentes utilizan sensores y datos para mejorar la calidad de vida urbana.",
    "الأقمار الصناعية توفر بيانات حيوية لرصد التغيرات المناخية والبيئية",
    "प्राकृतिक भाषा प्रसंस्करण मशीनों को मानव भाषा को समझने और उत्पन्न करने में सक्षम बनाता है।",
    "L'agriculture de précision utilise des drones et l'intelligence artificielle pour optimiser les rendements.",
    "Die Erforschung des menschlichen Gehirns ist eine der größten wissenschaftlichen Herausforderungen unserer Zeit.",
    "La edición genética CRISPR plantea importantes cuestiones éticas y regulatorias.",
    "تعلم الآلة الكمومي يجمع بين قدرات الحوسبة الكمومية وخوارزميات التعلم الآلي",
    "ब्लॉकचेन प्रौद्योगिकी वित्तीय लेनदेन में पारदर्शिता और सुरक्षा प्रदान करती है।",
    "La recherche fondamentale en physique des particules se poursuit au CERN avec le Grand collisionneur de hadrons.",
    "Quantensensoren ermöglichen präzisere Messungen als je zuvor in der Geschichte der Messtechnik.",
    "Los algoritmos de recomendación moldean lo que vemos, leemos y compramos en Internet.",
    "علم الأعصاب الحسابي يساعد في فهم كيفية معالجة الدماغ للمعلومات",
    "अंतरिक्ष प्रौद्योगिकी ने संचार, मौसम पूर्वानुमान और नेविगेशन में क्रांति ला दी है।",
]

MIXED_CONTENT = [
    "The API returned {status: 200, data: [{id: 1, name: 'test'}]} after 45ms latency.",
    "Use git rebase -i HEAD~3 to squash the last three commits before merging PR #1247.",
    "Einstein's E=mc² means that 1kg of matter contains 9×10¹⁴ joules of energy!",
    "The server at 192.168.1.100:8080 returned HTTP 503 — check the nginx.conf file.",
    "Fix bug #4521: the regex /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/ fails on .museum TLDs.",
    "Version 3.14.159 introduced breaking changes to the ConfigParser™ module's API.",
    "The SQL query took 2,847ms — add an index on (user_id, created_at DESC) to fix it.",
    "Docker image python:3.11-slim is 45MB vs ubuntu:22.04 at 77MB — use the former.",
    "The λ-calculus expression (λx.λy.x y) (λz.z) β-reduces to λy.(λz.z) y.",
    "Meeting notes: Q3 revenue was $4.2M (+18% YoY), EBITDA margin improved to 23.5%.",
    "Run pytest -xvs tests/test_auth.py::TestLogin::test_token_refresh to debug the CI failure.",
    "The UTF-8 encoding of '日' is 0xE6 0x97 0xA5 (3 bytes), while ASCII 'A' is just 0x41.",
    "According to RFC 2616 §14.9, Cache-Control: no-store prevents any caching by intermediaries.",
    "The YAML config needs: max_retries: 3\\n  timeout_ms: 5000\\n  endpoints:\\n    - https://api.prod.internal",
    "Prof. García's paper (arXiv:2401.12345) achieved 94.7% F1-score on the MMLU benchmark.",
    "Install with: pip install torch==2.1.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html",
    "The deadlock occurs when Thread-1 holds mutex_A and waits for mutex_B while Thread-2 does the reverse.",
    "CSS rule: .container { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; }",
    "MongoDB query: db.users.find({age: {$gte: 18}, 'address.city': 'NYC'}).sort({lastName: 1}).limit(100)",
    "The Mandelbrot set: z_{n+1} = z_n² + c, where c ∈ ℂ and |z| never exceeds 2.",
    "Kubernetes pod scheduling failed: 0/3 nodes available (2 Insufficient memory, 1 node(s) had taint).",
    "The O(n log n) sorting algorithm processes 10⁶ elements in ~20ms on an M2 MacBook Pro.",
    "Error in line 47 of main.py: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'",
    "The RSA-2048 key has a modulus of 617 digits: n = p × q where p,q are 1024-bit primes.",
    "Slack message @channel: Deploy v2.3.1 to prod at 14:00 UTC — ETA 15min, rollback plan in wiki/deploys.",
    "The transformer model has 175B parameters: 96 layers × 96 heads × d_model=12288.",
    "LaTeX: \\frac{\\partial^2 u}{\\partial t^2} = c^2 \\nabla^2 u describes wave propagation.",
    "AWS bill breakdown: EC2 ($12,450), S3 ($3,200), RDS ($8,900), Lambda ($450) = total $25,000/month.",
    "The WebSocket connection ws://localhost:3000/live sends heartbeat pings every 30s ± 5s jitter.",
    "Benchmark results: GPT-4o scored 88.7% on MATH, Claude 3.5 Sonnet scored 91.6% on HumanEval.",
    "The CIDR notation 10.0.0.0/24 covers IP addresses from 10.0.0.0 to 10.0.0.255 (256 hosts).",
    "React component: <DataGrid rows={filteredData} columns={cols} pageSize={25} onSort={handleSort} />",
    "The SHA-256 hash of 'hello' is 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824.",
    "Cron expression '0 */6 * * 1-5' runs at midnight, 6am, noon, 6pm on weekdays only.",
    "The neural network architecture: Input(784) → Dense(512, ReLU) → Dropout(0.3) → Dense(10, Softmax).",
    "Git bisect found the regression: commit a1b2c3d introduced NaN in the loss function on 2024-03-15.",
    "The TCP three-way handshake (SYN → SYN-ACK → ACK) completed in 12ms to endpoint 203.0.113.42:443.",
    "Terraform state shows 47 resources: 12 aws_instance, 8 aws_security_group, 5 aws_rds_instance, etc.",
    "The regex (?<=\\$)\\d+(?:\\.\\d{2})? matches dollar amounts like $99.99 and $1000 but not €50.",
    "JIRA ticket PROJ-4521: 'Users report 403 errors when accessing /api/v2/reports after SSO migration'.",
    "The FFT computes the DFT of N points in O(N log N) vs the naive O(N²) — crucial for real-time audio at 44.1kHz.",
    "Nginx config: location /api { proxy_pass http://upstream:8080; proxy_set_header X-Real-IP $remote_addr; }",
    "The PageRank algorithm: PR(A) = (1-d) + d × Σ(PR(T)/C(T)) where d=0.85 is the damping factor.",
    "Stack trace: at com.app.service.UserService.findById(UserService.java:42) ... 15 more frames.",
    "The bloom filter with k=7 hash functions and m=2^20 bits has a false positive rate of ~0.8% for n=10⁵ elements.",
    "GraphQL query: { user(id: \"u_123\") { name posts(first: 10, after: \"cursor_abc\") { edges { node { title } } } } }",
    "DNS resolution: example.com → CNAME api.example.cdn.net → A 104.26.10.53 (TTL: 300s).",
    "The B+ tree with order 256 and 10⁹ keys has a height of only ⌈log₂₅₆(10⁹)⌉ = 4 levels.",
    "Environment variables: DATABASE_URL=postgres://user:p@ss@db:5432/mydb?sslmode=require",
    "The LSTM cell: f_t = σ(W_f·[h_{t-1}, x_t] + b_f) controls the forget gate at each timestep.",
    "Prometheus alert: rate(http_requests_total{status=~\"5..\"}[5m]) / rate(http_requests_total[5m]) > 0.05",
    "The convex hull of 10,000 2D points was computed in 2.3ms using Graham scan — O(n log n).",
    "Release notes v4.0: ① Added OAuth2 PKCE flow ② Fixed race condition in cache invalidation ③ Dropped Python 3.7 support.",
    "Redis command: ZADD leaderboard 9850 \"player_42\" 9720 \"player_17\" 9680 \"player_91\"",
    "The EM algorithm alternates between E-step (compute Q(θ|θ_old)) and M-step (maximize Q) until convergence.",
    "Systemd unit: [Service] ExecStart=/usr/bin/app --port=8080 Restart=always RestartSec=5 MemoryMax=2G",
    "The mutual TLS handshake requires both client.pem and server.pem certificates signed by the same CA.",
    "Profiling shows: 68% of CPU time in matmul(), 15% in softmax(), 12% in layer_norm(), 5% other.",
    "The consistent hash ring with 150 virtual nodes per server achieves <10% key redistribution on node failure.",
    "Makefile: build: $(CC) $(CFLAGS) -o $(TARGET) $(SRCS) -lm -lpthread",
    "The attention mechanism: Attention(Q,K,V) = softmax(QK^T/√d_k)V where d_k is the key dimension.",
    "Load test results: p50=12ms, p90=45ms, p95=120ms, p99=850ms at 10,000 RPS with 99.97% availability.",
    "The Merkle tree root hash verifies the integrity of all 2^20 leaf nodes with only 20 hash comparisons.",
    "Elasticsearch query: {\"bool\": {\"must\": [{\"match\": {\"title\": \"neural\"}}, {\"range\": {\"date\": {\"gte\": \"2024-01-01\"}}}]}}",
    "Assembly: mov rax, [rbp-8]; imul rax, rcx; add rax, rdx; — computes a*b+c in 3 instructions.",
    "The HyperLogLog algorithm estimates cardinality of 10⁹ unique elements using only 12KB of memory (±0.81% error).",
    "OpenTelemetry span: trace_id=abc123 span_id=def456 parent_id=ghi789 operation='db.query' duration=23ms status=OK",
    "Compiler optimization -O3 reduced binary size from 4.2MB to 2.8MB and improved throughput by 37%.",
    "The CAP theorem states: in a distributed system, you can have at most 2 of {Consistency, Availability, Partition tolerance}.",
    "Rate limiting: 100 requests/minute per API key, with token bucket algorithm (burst=20, refill=1.67/sec).",
    "The Raft consensus protocol requires ⌊n/2⌋+1 votes to elect a leader in a cluster of n nodes.",
    "CI/CD pipeline: lint (30s) → test (4m) → build (2m) → deploy-staging (1m) → e2e (8m) → deploy-prod (1m).",
    "WebAssembly module: (func $add (param $a i32) (param $b i32) (result i32) local.get $a local.get $b i32.add)",
    "The skip list with p=0.5 has expected O(log n) search time and uses O(n) space on average.",
    "Linux perf: cache-misses 2.3% of cache-references, branch-misses 0.8%, IPC 2.4 instructions/cycle.",
    "The Aho-Corasick automaton matches k patterns of total length m in O(n + m + z) time, where z = number of matches.",
    "S3 lifecycle rule: transition to GLACIER after 90 days, delete after 365 days, for objects in logs/ prefix.",
    "The ZAB protocol in ZooKeeper ensures total order broadcast with 2f+1 servers tolerating f failures.",
    "gRPC service definition: rpc SearchProducts(SearchRequest) returns (stream ProductResult) {}",
    "CPU cache hierarchy: L1d=32KB/4cycles, L2=256KB/12cycles, L3=8MB/40cycles, RAM=64GB/~200cycles.",
    "The LSM tree compacts SSTables via merge-sort: Level0 (64MB) → Level1 (640MB) → Level2 (6.4GB).",
    "Network packet: [Ethernet 14B][IP 20B][TCP 20B][TLS 5B][HTTP/2 9B][payload 1200B] = 1268B total.",
    "The Robin Hood hashing scheme achieves average O(1) lookups with variance σ²=O(log log n) probe length.",
    "Kafka partition assignment: topic 'events' with 12 partitions across 3 brokers, replication-factor=3.",
    "SIMD instruction: _mm256_fmadd_ps(a, b, c) computes 8 float multiply-adds in a single AVX2 cycle.",
    "The phi coefficient φ = (TP×TN - FP×FN) / √((TP+FP)(TP+FN)(TN+FP)(TN+FN)) measures binary classification quality.",
    "JWT payload: {\"sub\": \"user_42\", \"iss\": \"auth.example.com\", \"exp\": 1711234567, \"roles\": [\"admin\", \"editor\"]}",
    "The Bézier curve B(t) = (1-t)³P₀ + 3(1-t)²tP₁ + 3(1-t)t²P₂ + t³P₃ for t ∈ [0,1].",
    "Memory layout: stack (grows ↓), heap (grows ↑), BSS, data, text — total virtual address space 2⁴⁸ bytes on x86-64.",
    "The CRC-32 polynomial x³²+x²⁶+x²³+x²²+x¹⁶+x¹²+x¹¹+x¹⁰+x⁸+x⁷+x⁵+x⁴+x²+x+1 detects all burst errors ≤32 bits.",
]

EDGE_CASES = [
    "https://www.example.com/path/to/resource?param1=value1&param2=value2#section-3",
    "user.name+tag@subdomain.example.co.uk",
    "🎉🎊🎈🎁🎂🥳🍾🎆🎇✨💫⭐🌟💥🔥",
    "pneumonoultramicroscopicsilicovolcanoconiosis",
    "!!!???...---___===+++///\\\\\\|||@@@###$$$%%%^^^&&&***((()))",
    "C:\\Users\\Administrator\\AppData\\Local\\Temp\\file (1) (copy).txt.bak",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "a]b[c{d}e(f)g<h>i'j\"k`l~m!n@o#p$q%r^s&t*u-v_w+x=y|z",
    "   \t\t\t   leading and trailing whitespace   \t\t\t   ",
    "the quick brown fox jumps over the lazy dog THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG",
    "192.168.0.1 10.0.0.0/8 172.16.0.0/12 255.255.255.0 ::1 fe80::1%eth0 2001:db8::1",
    "3.14159265358979323846264338327950288419716939937510",
    "¡Hola! ¿Cómo estás? Ça va bien, merci. Über cool! Naïve café résumé",
    "→←↑↓↔↕↖↗↘↙⇒⇐⇑⇓⇔⇕",
    "SELECT * FROM users WHERE name = 'O''Brien' AND status != 'deleted'; -- SQL injection test",
    "file:///usr/local/share/doc/README.md#L42-L50",
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk",
    "2024-03-15T14:30:00.000Z 1710510600 Fri Mar 15 2024 14:30:00 GMT+0000",
    "\u0000\u0001\u0002\u0003\u0004\u0005 null bytes and control characters \u0007\u0008",
    "α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ σ τ υ φ χ ψ ω",
    "🧑‍💻👨‍👩‍👧‍👦🏳️‍🌈🇺🇸🇯🇵🇩🇪🇫🇷🇨🇳🇮🇳🇧🇷",
    "supercalifragilisticexpialidocious antidisestablishmentarianism floccinaucinihilipilification",
    "1234567890 0xDEADBEEF 0b10101010 0o777 1.23e-45 6.022e23 NaN Infinity -0",
    "McDonald's Häagen-Dazs Toys\"R\"Us AT&T Yahoo! Mötley Crüe naïve café",
    "{\"nested\": {\"deeply\": {\"structured\": {\"json\": {\"with\": {\"many\": {\"levels\": true}}}}}}}",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "CamelCaseIdentifier snake_case_name kebab-case-class SCREAMING_SNAKE_CASE mixedCase123Name",
    "\\n\\t\\r\\0\\\\ \\' \\\" \\x41 \\u0041 \\U00000041 \\N{LATIN SMALL LETTER A}",
    "𝕳𝖊𝖑𝖑𝖔 𝕎𝕠𝕣𝕝𝕕 𝐇𝐞𝐥𝐥𝐨 𝑾𝒐𝒓𝒍𝒅 ℍ𝕖𝕝𝕝𝕠",
    "+1 (555) 123-4567 +44 20 7946 0958 +81 3-1234-5678 +91 98765 43210",
    "v1.2.3-beta.1+build.456 ~1.0.0 ^2.3.x >=1.0.0 <2.0.0 1.0.0 || 2.0.0",
    "GET /api/v2/users?page=1&limit=50&sort=-created_at&filter[status]=active HTTP/1.1",
    "The 1st, 2nd, 3rd, 4th, 5th, 21st, 22nd, 23rd, 100th, 101st items.",
    "I can't won't shouldn't couldn't wouldn't don't isn't aren't wasn't weren't",
    "e.g., i.e., etc., vs., Dr., Mr., Mrs., Ms., Jr., Sr., Inc., Ltd., Corp.",
    "foo.bar.baz().qux[0].method('arg1', kwarg=True).chain().result",
    "    if (x > 0) {\n        return x * factorial(x - 1);\n    } else {\n        return 1;\n    }",
    "Copyright © 2024 Acme Corp™. All rights reserved®. Patent pending℠.",
    "⌘C ⌘V ⌘Z ⌘⇧S Ctrl+Alt+Del Alt+F4 ⌥⌘I F12",
    "The temperature was -40°F (-40°C) — the point where Fahrenheit and Celsius scales converge.",
    "ssh -i ~/.ssh/id_ed25519 -L 8080:localhost:3000 -J bastion@jump.example.com user@internal.server",
    "½ ⅓ ¼ ⅕ ⅙ ⅐ ⅛ ⅑ ⅒ ⅔ ¾ ⅖ ⅗ ⅘ ⅚ ⅝ ⅞",
    "道可道，非常道。名可名，非常名。無名天地之始；有名萬物之母。",
    "Ελληνικά Кириллица العربية עברית ไทย 한국어 বাংলা தமிழ் ᐃᓄᒃᑎᑐᑦ",
    "𓀀𓀁𓀂𓀃𓀄 𐎀𐎁𐎂𐎃 𒀀𒀁𒀂𒀃 ꡀꡁꡂꡃ",
    "    \u200B\u200B\u200B zero-width spaces \u200B\u200B\u200B and\u00A0non-breaking\u00A0spaces\u00A0here",
    "R̈öck döts ëvërÿwhërë Motörhead Mötley Crüe Queensrÿche Löwenbräu",
    "2⁰=1 2¹=2 2²=4 2³=8 2⁴=16 2⁵=32 2⁶=64 2⁷=128 2⁸=256 2⁹=512 2¹⁰=1024",
    "Z̤̈ä̤l̤̈g̤̈ö̤ ̤̈ẗ̤ë̤ẍ̤ẗ̤ with combining diacritical marks",
    "rm -rf / ; DROP TABLE users; <script>alert('xss')</script> ${USER} $(whoami)",
    "🏴󠁧󠁢󠁥󠁮󠁧󠁿🏴󠁧󠁢󠁳󠁣󠁴󠁿🏴󠁧󠁢󠁷󠁬󠁳󠁿 regional flag sequences",
    "a\u0300 a\u0301 a\u0302 a\u0303 a\u0308 a\u030A c\u0327 n\u0303 o\u0308 u\u0308 combining characters vs precomposed àáâãäåçñöü",
    "The file sizes are: 1B, 1KB, 1MB, 1GB, 1TB, 1PB, 1EB, 1ZB, 1YB.",
    "Error: ECONNREFUSED 127.0.0.1:5432 ETIMEDOUT ENOENT EPERM EACCES ENOSPC EMFILE",
    "www.example.com example.com http://example.com https://example.com ftp://files.example.com",
    "Line 1\nLine 2\rLine 3\r\nLine 4\n\nLine 6\n\n\nLine 9",
    "Tab\there\tand\there\t\t\tdouble\t\ttabs",
    ".hidden_file ..parent_dir ...ellipsis ....four_dots",
    "It costs $99.99 or €89.99 or £79.99 or ¥10,800 or ₹7,499 or ₩119,000.",
    "H₂O CO₂ O₂ N₂ CH₄ C₂H₅OH NaCl H₂SO₄ Fe₂O₃ Ca(OH)₂",
    "🔴🟠🟡🟢🔵🟣⚫⚪🟤 ♠♣♥♦ ♔♕♖♗♘♙ ☀☁☂☃☄★☆",
    "ASCII art: /\\_/\\ ( o.o ) > ^ < meow!",
    "The path /usr/local/bin/../lib/./python3.11/site-packages normalizes to /usr/local/lib/python3.11/site-packages",
    "Regex lookahead/behind: (?<=@)\\w+(?=\\.com) matches 'gmail' in user@gmail.com",
    "Mixed numbers: forty-two 42 XLII 0x2A 0b101010 052 '42' \"42\"",
    "Paired brackets: () [] {} <> «» "" '' ‹› 【】 「」 『』 （）",
    "Math operators: + − × ÷ ± ≠ ≈ ≤ ≥ ∞ ∑ ∏ ∫ √ ∂ ∇ ∈ ∉ ⊂ ⊃ ∪ ∩ ∀ ∃",
    "Typographic: — – - ‐ ‑ ' ' " " „ ‚ … · • ° ′ ″ ‰ ※",
    "Musical: ♩♪♫♬ 𝄞𝄢 ♭♮♯ 𝅝𝅗𝅥𝅘𝅥𝅘𝅥𝅮𝅘𝅥𝅯",
    "Box drawing: ┌─┬─┐ │ │ │ ├─┼─┤ │ │ │ └─┴─┘",
    "Braille: ⠓⠑⠇⠇⠕ ⠺⠕⠗⠇⠙",
    "The string 'café' has 4 chars but 5 bytes in UTF-8 (63 61 66 C3 A9).",
    "Backslash madness: C:\\\\Users\\\\name or /home/user or ~user/.config",
    "Entity references: &amp; &lt; &gt; &quot; &#x41; &#65; &copy; &mdash; &nbsp;",
    "Invisible characters: \u200E\u200F left-to-right and right-to-left marks \u200E\u200F",
    "Phone: tel:+15551234567 mailto:user@example.com sms:+15559876543?body=Hello",
    "The word 'set' has 430 definitions in the Oxford English Dictionary, making it the longest entry.",
    "UUID: 550e8400-e29b-41d4-a716-446655440000 ULID: 01ARZ3NDEKTSV4RRFFQ69G5FAV",
    "MIME types: application/json text/html image/png audio/mpeg video/mp4 font/woff2",
    "HTTP headers: Content-Type: application/json; charset=utf-8\\r\\nX-Request-ID: abc-123",
    "The 'buffalo buffalo buffalo buffalo buffalo buffalo buffalo buffalo' sentence is grammatically correct.",
    "Time zones: UTC+0 EST-5 PST-8 IST+5:30 JST+9 AEST+10 NZST+12 CHAT+12:45",
    "Binary: 01001000 01100101 01101100 01101100 01101111 = 'Hello' in ASCII",
    "Emoji modifiers: 👋🏻👋🏼👋🏽👋🏾👋🏿 skin tone variants of waving hand",
    "The pangram: 'Cwm fjord veg balks nth pyx quiz.' uses all 26 letters.",
    "Heredoc: <<'EOF'\\nThis is $not interpolated\\nEOF vs <<EOF\\nThis is $interpolated\\nEOF",
    "URL encoding: Hello%20World%21 = 'Hello World!' and caf%C3%A9 = 'café'",
    "Git SHA: a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0 (full) vs a1b2c3d (short)",
    "ANSI escapes: \\033[31mRed\\033[0m \\033[1;32mBold Green\\033[0m \\033[4;34mUnderline Blue\\033[0m",
    "Ligatures: ﬁ ﬂ ﬀ ﬃ ﬄ æ Æ œ Œ ß ẞ ĳ Ĳ",
    "Roman numerals: Ⅰ Ⅱ Ⅲ Ⅳ Ⅴ Ⅵ Ⅶ Ⅷ Ⅸ Ⅹ Ⅺ Ⅻ Ⅼ Ⅽ Ⅾ Ⅿ",
]


def get_corpus() -> list[tuple[str, str]]:
    """Return list of (sentence, category) tuples."""
    corpus = []
    for s in SIMPLE_ENGLISH:
        corpus.append((s, "simple_english"))
    for s in COMPLEX_ENGLISH:
        corpus.append((s, "complex_english"))
    for s in CODE_SNIPPETS:
        corpus.append((s, "code"))
    for s in MATHEMATICAL:
        corpus.append((s, "mathematical"))
    for s in CJK_SENTENCES:
        corpus.append((s, "cjk"))
    for s in MULTILINGUAL:
        corpus.append((s, "multilingual"))
    for s in MIXED_CONTENT:
        corpus.append((s, "mixed"))
    for s in EDGE_CASES:
        corpus.append((s, "edge_cases"))
    return corpus


def get_example_sentences() -> list[tuple[str, str]]:
    """Return 5 representative sentences for alignment visualization."""
    return [
        (SIMPLE_ENGLISH[0], "simple_english"),
        (COMPLEX_ENGLISH[0], "complex_english"),
        (CODE_SNIPPETS[0], "code"),
        (CJK_SENTENCES[0], "cjk"),
        (MIXED_CONTENT[0], "mixed"),
    ]
